### ISSUE TITLE
About vsrl_eval.py and an error occurred during the test.

### ISSUE THREAD

**Issue by YSN1011** [SiyuanQi/gpnn#23]
Dear Authors,

Thank you very much for releasing the code (https://github.com/SiyuanQi/gpnn) of your GPNN for HOI work. I'd like to ask you some questions.
1.The vsrl_eval.py file is under the VCOCO data set. Should I put it in the same directory as the VCOCO. Py file?If not, I will display an impot error.
2.When I test, the following error will be shown.KeyError: u'stand_agent'. Is it because the PKL file generated by my training is not correct?

**Comment by Kebii** [comment]
Have you solved the third question?
I meet the same problem.

Traceback (most recent call last):
  File "vcoco.py", line 465, in <module>
    main(args)
  File "vcoco.py", line 277, in main
    validate(args, test_loader, model, mse_loss, multi_label_loss, test_vcocoeval, test=True)
  File "vcoco.py", line 395, in validate
    vcoco_evaluation(args, vcocoeval, 'test', all_results)
  File "vcoco.py", line 117, in vcoco_evaluation
    vcocoeval._do_eval(det_file, ovr_thresh=0.5)
  File "/mnt/data/zjx/Repository/gpnn/src/python/vsrl_eval.py", line 193, in _do_eval
    self._do_agent_eval(vcocodb, detections_file, ovr_thresh=ovr_thresh)
  File "/mnt/data/zjx/Repository/gpnn/src/python/vsrl_eval.py", line 354, in _do_agent_eval
    pred_agents, _ = self._collect_detections_for_image(dets, image_id)
  File "/mnt/data/zjx/Repository/gpnn/src/python/vsrl_eval.py", line 185, in _collect_detections_for_image
    this_role[0, 5 * aid: 5 * aid + 5, j-1] = det[self.actions[aid] + '_' + rid]
KeyError: 'hold_obj'
