### ISSUE TITLE
Module import failure is displayed when it is in a folder

### ISSUE THREAD

**Issue by 2589996558** [SiyuanQi/gpnn#33]
D:\develop\python\3.12.5\python.exe D:\Download\gpnn-master\src\python\hico.py 
D:\Download\gpnn-master\src\python\hico.py:343: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if sequence_ids[0] is 'HICO_test2015_00000396':
Traceback (most recent call last):
  File "D:\Download\gpnn-master\src\python\hico.py", line 20, in <module>
    import datasets
  File "D:\Download\gpnn-master\src\python\datasets\__init__.py", line 1, in <module>
    from .CAD120.cad120 import CAD120
  File "D:\Download\gpnn-master\src\python\datasets\CAD120\cad120.py", line 18, in <module>
    import cad120_config
ModuleNotFoundError: No module named 'cad120_config'

Process finished with exit code 1

**Comment by Zhang-Zhaoji** [comment]
use from . import cad120_config instead
